### ISSUE TITLE
Stunning veiled elites with Captain's stun beacon produce an insane amount of particles

### ISSUE THREAD

**Issue by DarSitam** [prodzpod/NemesisSpikestrip#2]
**How to reproduce :**

- play Captain, with the stun beacon
- Lure a veiled elite into the stun beacon

![image](https://github.com/prodzpod/NemesisSpikestrip/assets/106157297/83f8937c-2b99-4b30-abec-4ebebfad51b2)

**Comment by prodzpod** [comment]
fixed this update
