### ISSUE TITLE
Plated elite NRE

### ISSUE THREAD

**Issue by goldenguy00** [prodzpod/NemesisSpikestrip#3]
NRE on plated elite's hook for HealthComponent.TakeDamage because unity sucks.

Since you used `CharacterBody? body = damageInfo.attacker?.GetComponent<CharacterBody>();` the attacker get compared with the true C# nullref and not the Unity NullPtr that it wants you to use. attacker is the new delayed damage echo item, so should eval to null here but Unity is wonderful, so it doesnt. The GetComponent call goes through and code goes boom. I'm willing to bet the `CharacterBody?` variable type is the problem and that its not using the right `==` operator. Literally one character caused this. Fun times all around.

![{C1ECAEA5-51D8-4047-90EA-271A8B8F364A}](https://github.com/user-attachments/assets/a5ba2327-9a12-4a3c-a8cb-07aa41dc5183)

`[Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.GameObject.GetComponent[T] () (at <a20b3695b7ce4017b7981f9d06962bd1>:IL_0021)
NemesisSpikestrip.Changes.Plated+<>c.<Init>b__9_0 (On.RoR2.HealthComponent+orig_TakeDamage orig, RoR2.HealthComponent self, RoR2.DamageInfo damageInfo) (at <8bc02b7824c1484e941531ffcc08926d>:IL_010E)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoR2.HealthComponent::TakeDamage>?-2051095508(RoR2.HealthComponent,RoR2.DamageInfo)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<RoR2.HealthComponent::TakeDamage>?-939575154(RoR2.HealthComponent,RoR2.DamageInfo)
StormTweaks.CHEF.HealthComponent_TakeDamage (On.RoR2.HealthComponent+orig_TakeDamage orig, RoR2.HealthComponent self, RoR2.DamageInfo damageInfo) (at <c37744e435a343b0b085d05499613738>:IL_00CA)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoR2.HealthComponent::TakeDamage>?-589586640(RoR2.HealthComponent,RoR2.DamageInfo)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<RoR2.HealthComponent::TakeDamage>?-216536906(RoR2.HealthComponent,RoR2.DamageInfo)
EnforcerPlugin.EnforcerModPlugin.HealthComponent_TakeDamage (On.RoR2.HealthComponent+orig_TakeDamage orig, RoR2.HealthComponent self, RoR2.DamageInfo info) (at <1f209e2f09e441fe9c29d6e6ef9865c1>:IL_02A5)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoR2.HealthComponent::TakeDamage>?1654158056(RoR2.HealthComponent,RoR2.DamageInfo)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<RoR2.HealthComponent::TakeDamage>?-565488784(RoR2.HealthComponent,RoR2.DamageInfo)
ThinkInvisible.TinkersSatchel.MotionTracker.HealthComponent_TakeDamage (On.RoR2.HealthComponent+orig_TakeDamage orig, RoR2.HealthComponent self, RoR2.DamageInfo damageInfo) (at <8f4cb1ba5a0c4a68b32f3630921e431b>:IL_0000)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoR2.HealthComponent::TakeDamage>?-60870124(RoR2.HealthComponent,RoR2.DamageInfo)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<RoR2.HealthComponent::TakeDamage>?-2093560054(RoR2.HealthComponent,RoR2.DamageInfo)
ThinkInvisible.TinkersSatchel.Skein.HealthComponent_TakeDamage (On.RoR2.HealthComponent+orig_TakeDamage orig, RoR2.HealthComponent self, RoR2.DamageInfo damageInfo) (at <8f4cb1ba5a0c4a68b32f3630921e431b>:IL_0094)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoR2.HealthComponent::TakeDamage>?1683986340(RoR2.HealthComponent,RoR2.DamageInfo)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<RoR2.HealthComponent::TakeDamage>?1352498420(RoR2.HealthComponent,RoR2.DamageInfo)
RA2Mod.Hooks.RoR2.HealthComponent+TakeDamageHook.HealthComponent_TakeDamage (On.RoR2.HealthComponent+orig_TakeDamage orig, RoR2.HealthComponent self, RoR2.DamageInfo damageInfo) (at <daaf86eded074fa79e2ca34246830023>:IL_0013)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoR2.HealthComponent::TakeDamage>?1244392828(RoR2.HealthComponent,RoR2.DamageInfo)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<RoR2.HealthComponent::TakeDamage>?-1778216246(RoR2.HealthComponent,RoR2.DamageInfo)
SS2.Survivors.NemCommando.TakeDamageGouge (On.RoR2.HealthComponent+orig_TakeDamage orig, RoR2.HealthComponent self, RoR2.DamageInfo damageInfo) (at <cf719a4ae0604dea853a05835a392545>:IL_0070)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoR2.HealthComponent::TakeDamage>?-1029486628(RoR2.HealthComponent,RoR2.DamageInfo)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<RoR2.HealthComponent::TakeDamage>?-441572518(RoR2.HealthComponent,RoR2.DamageInfo)
SS2.Survivors.Engineer.EngiFocusDamageHook (On.RoR2.HealthComponent+orig_TakeDamage orig, RoR2.HealthComponent self, RoR2.DamageInfo damageInfo) (at <cf719a4ae0604dea853a05835a392545>:IL_009E)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoR2.HealthComponent::TakeDamage>?1901179184(RoR2.HealthComponent,RoR2.DamageInfo)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<RoR2.HealthComponent::TakeDamage>?395635568(RoR2.HealthComponent,RoR2.DamageInfo)
SS2.AttackerOverrideManager.OverrideTakeDamage (On.RoR2.HealthComponent+orig_TakeDamage orig, RoR2.HealthComponent self, RoR2.DamageInfo damageInfo) (at <cf719a4ae0604dea853a05835a392545>:IL_006C)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoR2.HealthComponent::TakeDamage>?2062850528(RoR2.HealthComponent,RoR2.DamageInfo)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<RoR2.HealthComponent::TakeDamage>?-72692368(RoR2.HealthComponent,RoR2.DamageInfo)
FRCSharp.FRHooks.HealthComponent_TakeDamage (On.RoR2.HealthComponent+orig_TakeDamage orig, RoR2.HealthComponent self, RoR2.DamageInfo damageInfo) (at <25f4fbe43fa241a28b9fd1062787718f>:IL_0007)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoR2.HealthComponent::TakeDamage>?283127316(RoR2.HealthComponent,RoR2.DamageInfo)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<RoR2.HealthComponent::TakeDamage>?517319370(RoR2.HealthComponent,RoR2.DamageInfo)
ArsonistMod.Content.Controllers.MasochismController.HealthComponent_TakeDamage (On.RoR2.HealthComponent+orig_TakeDamage orig, RoR2.HealthComponent self, RoR2.DamageInfo damageInfo) (at <03ce78c61b2747a1a0daff6fb9120f10>:IL_00BD)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoR2.HealthComponent::TakeDamage>?-1303380856(RoR2.HealthComponent,RoR2.DamageInfo)
(wrapper dynamic-method) RoR2.DotController.DMD<RoR2.DotController::EvaluateDotStacksForType>(RoR2.DotController,RoR2.DotController/DotIndex,single,int&)
(wrapper dynamic-method) RoR2.DotController.DMD<RoR2.DotController::FixedUpdate>(RoR2.DotController)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<RoR2.DotController::FixedUpdate>?137697278(RoR2.DotController)
R2API.DotAPI.FixedUpdate (On.RoR2.DotController+orig_FixedUpdate orig, RoR2.DotController self) (at <a7c79dc937e64cd39f8b2240b0f27583>:IL_0000)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoR2.DotController::FixedUpdate>?-1908685668(RoR2.DotController)
`

**Comment by prodzpod** [comment]
love unity

**Comment by prodzpod** [comment]
should be fixed
